version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_HOST:
      MYSQL_DATABASE: petshop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./petshop_data:/var/lib/mysql

  springBootPetShop:
    build:
      context: ./
      dockerfile: DockerFile
    image: app.jar
    ports:
      - "8080:8080"
volumes:
  petshop_data: