FROM maven:3.8-openjdk-17
RUN mkdir -p /src/app
ADD . /src/app
WORKDIR /src/app
RUN mvn package -Dmaven.test.skip=true
COPY /target/springBootPetShop-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java","-jar", "app.jar"]